DROP TABLE IF EXISTS users, items, bookings, comments, requests;

CREATE table IF NOT EXISTS users(
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(40),
    name varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS requests(
	request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description varchar(200),
	requestor_id bigint REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE table IF NOT EXISTS items(
    item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(200) NOT NULL,
    is_available boolean,
    owner_id bigint REFERENCES users (user_id) ON DELETE CASCADE,
    request_id bigint REFERENCES requests (request_id) ON DELETE CASCADE
);

CREATE table IF NOT EXISTS bookings(
    booking_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    item_id bigint REFERENCES items (item_id) ON DELETE CASCADE,
    booker_id bigint REFERENCES users (user_id) ON DELETE CASCADE,
    status varchar NOT NULL
);

CREATE table IF NOT EXISTS comments(
    comment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(1000) NOT NULL,
    created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    item_id bigint REFERENCES items (item_id) ON DELETE CASCADE,
    author_id bigint REFERENCES users (user_id) ON DELETE CASCADE
);