DROP TABLE IF EXISTS users, items, bookings, comments CASCADE;

CREATE table IF NOT EXISTS users(
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(40) NOT NULL,
    name varchar(30) NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE table IF NOT EXISTS item_requests(
    request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(500),
    requester bigint REFERENCES users(user_id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE
);

CREATE table IF NOT EXISTS items(
    item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(200) NOT NULL,
    is_available boolean,
    owner_id bigint REFERENCES users (user_id) ON DELETE CASCADE,
    request_id bigint REFERENCES item_requests(request_id)
);

CREATE table IF NOT EXISTS bookings(
    booking_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date timestamp(9) without time zone,
    end_date timestamp(9) without time zone,
    item_id bigint REFERENCES items (item_id) ON DELETE CASCADE,
    booker_id bigint REFERENCES users (user_id) ON DELETE CASCADE,
    status varchar(25) NOT NULL
);

CREATE table IF NOT EXISTS comments(
    comment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(1000) NOT NULL,
    created timestamp(9) without time zone DEFAULT CURRENT_TIMESTAMP,
    item_id bigint REFERENCES items (item_id) ON DELETE CASCADE,
    author_id bigint REFERENCES users (user_id) ON DELETE CASCADE
);